name: eco
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  firebase_storage: ^12.3.0
  firebase_core: ^3.4.1
  introduction_screen: ^3.1.14
  carousel_slider: ^5.0.0
  get: ^4.6.5   # Add the get package
  firebase_analytics: ^11.3.1
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # The assets section should be properly indented
  assets:
    - assets/welcome.png

